const ah = document.getElementById("ah");
const abo = document.getElementById("abo");
const aw = document.getElementById("aw");
const as = document.getElementById("as");
const ac = document.getElementById("ac");
const ho = document.getElementById("ho");
const ab = document.getElementById("ab");
const wo = document.getElementById("wo");
const se = document.getElementById("se");
const co = document.getElementById("co");
const bt = document.getElementById("bt");
const msg = document.getElementById("msg");
ah.addEventListener("click", function () {
  ab.style.marginTop = "45px";
  ho.style.marginTop = "0px";
  wo.style.marginTop = "45px";
  se.style.marginTop = "45px";
  co.style.marginTop = "45px";
  ho.style.transition = "0.5s";
  ho.style.color = "#56AD82";
  ah.style.color = "#56AD82";
  ab.style.color = "#0d0c22";
  abo.style.color = "#0d0c22";
  wo.style.color = "#0d0c22";
  se.style.color = "#0d0c22";
  as.style.color = "#0d0c22";
  aw.style.color = "#0d0c22";
  co.style.color = "#0d0c22";
  ac.style.color = "#0d0c22";
});
abo.addEventListener("click", function () {
  ab.style.marginTop = "0px";
  ho.style.marginTop = "45px";
  wo.style.marginTop = "45px";
  se.style.marginTop = "45px";
  co.style.marginTop = "45px";
  ab.style.transition = "0.5s";
  ho.style.transition = "0.5s";
  ab.style.color = "#56AD82";
  abo.style.color = "#56AD82";
  ho.style.color = "#0d0c22";
  ah.style.color = "#0d0c22";
  wo.style.color = "#0d0c22";
  as.style.color = "#0d0c22";
  se.style.color = "#0d0c22";
  aw.style.color = "#0d0c22";
  co.style.color = "#0d0c22";
  ac.style.color = "#0d0c22";
});
aw.addEventListener("click", function () {
  wo.style.marginTop = "0px";
  se.style.marginTop = "45px";
  ab.style.marginTop = "45px";
  ho.style.marginTop = "45px";
  co.style.marginTop = "45px";
  wo.style.transition = "0.5s";
  ho.style.transition = "0.5s";
  wo.style.color = "#56AD82";
  aw.style.color = "#56AD82";
  ab.style.color = "#0d0c22";
  abo.style.color = "#0d0c22";
  ho.style.color = "#0d0c22";
  se.style.color = "#0d0c22";
  as.style.color = "#0d0c22";
  ah.style.color = "#0d0c22";
  co.style.color = "#0d0c22";
  ac.style.color = "#0d0c22";
});
as.addEventListener("click", function () {
  wo.style.marginTop = "45px";
  se.style.marginTop = "0px";
  ab.style.marginTop = "45px";
  ho.style.marginTop = "45px";
  co.style.marginTop = "45px";
  se.style.transition = "0.5s";
  ho.style.transition = "0.5s";
  wo.style.color = "#0d0c22";
  aw.style.color = "#0d0c22";
  ab.style.color = "#0d0c22";
  abo.style.color = "#0d0c22";
  ho.style.color = "#0d0c22";
  se.style.color = "#56AD82";
  as.style.color = "#56AD82";
  ah.style.color = "#0d0c22";
  co.style.color = "#0d0c22";
  ac.style.color = "#0d0c22";
});
ac.addEventListener("click", function () {
  co.style.marginTop = "0px";
  ab.style.marginTop = "45px";
  ho.style.marginTop = "45px";
  wo.style.marginTop = "45px";
  se.style.marginTop = "45px";
  co.style.transition = "0.5s";
  ho.style.transition = "0.5s";
  co.style.color = "#56AD82";
  ac.style.color = "#56AD82";
  ab.style.color = "#0d0c22";
  as.style.color = "#0d0c22";
  abo.style.color = "#0d0c22";
  wo.style.color = "#0d0c22";
  se.style.color = "#0d0c22";
  aw.style.color = "#0d0c22";
  ho.style.color = "#0d0c22";
  ah.style.color = "#0d0c22";
});

document.getElementById("bt").addEventListener("click", function () {
  var msg = document.getElementById("msg");
  msg.classList.remove("animate");
  void msg.offsetWidth;
  msg.classList.add("animate");
});
